export class ORMTaskSave {
    task_id:number;
	title:string;
	detail:string;
	type:string;
	priority:string;
	status:string;
	due_date:string;
	date_completed:string;
	completed_user:string;
	assigned_from:string;
	assigned_to:string;
	patient_id:number;
	chart_id:number;
	claim_id:number;
	practice_id:number;
	created_user:string;
	modified_user:string;
	date_created:string;
	date_modified:string;
	client_date_created:string;
	client_date_modified:string;	
	system_ip:string;
	operation_performed:string;
}