export class ORMSaveSetupFacility{
    facility_id:string;
		name:string;
		default_pos:string;
		phone:string;
		fax:string;
		email:string;
		address:string;
		city:string;
		state:string;
		zip:string;
		clia_number:string;
		clia_expiry_date:string;
		practice_id:string;
		deleted:boolean;
		created_user:string;
		date_created:string;
		modified_user:string;
		date_modified:string;
		client_date_created:string;
		client_date_modified:string;
		default_facility:boolean;
		npi:string;
}