export class ORMSaveReferral{
referral_id:string;
last_name:string;
mname:string;
first_name:string;
zip:string;
city:string;
state:string;
address:string;
phone:string;
fax:string;
email:string;
contact_person:string;
tax_id:string;
license:string;
upin:string;
ssn:string;
taxonomy_code:string;
npi:string;
reffering_type:string;
practice_id:string;
deleted:boolean;
created_user:string;
client_date_created:string;
modified_user:string;
client_date_modified:string;
date_created:string;
date_modified:string;
system_ip:string;
title:string;
consult_type_id:string;

}