export class ORMSaveSetupLabCategoryDetail
{
    detail_id:string;
    sub_category_id:string;
    proc_code:string;
    proc_description:string;
    units:string;
    test_instructions:string;
    deleted:boolean;
    created_user:string;
    client_date_created:string;
    modified_user:string;
    client_date_modified:string;
    date_created:string;
    date_modified:string;
    lab_assigned_cpt:string;
    lab_assigned_desc:string;
    system_ip:string;
    amount:string;
    modifier:string;
    ndc:string;
    position:string;
    practice_id:string;
}