export class ORMAPIUserSave {
    user_id:number;
    user_type:string;
    user_name:string;
    password:string;
    first_name:string;
    last_name:string;
    email:string;
    contact_no:string;
    can_access_all_patients:boolean;
    practice_id:number;
    is_blocked:boolean;
    created_user:string;
    date_created:string;
    client_date_created:string;
    modified_user:string;
    date_modified:string;
    client_date_modified:string;
    system_ip:string;
    user_rights:string;
}