export class ORMSavePatientInsurance {
    patientinsurance_id:Number;
    insurance_id:Number;
    patient_id:Number;
    insurace_type:String;
    policy_number:String;
    group_number:String;
    copay:String;
    start_date:String;
    end_date:String;
    guarantor_id:Number;
    guarantor_relationship:String;    
    created_user:String;
    client_date_created:String;
    modified_user:String;
    client_date_modified:String;
    date_created:String;
    date_modified:String;
    workercomp_name:String;
    workercomp_address:String;
    workercomp_city:String;
    workercomp_state:String;
    workercomp_zip:String;
    document_id:Number;
    pcp:String;
    system_ip:String;
}