export class ClamSavePro {
    claim_id: number;
    practice_id: number;
    patient_id: number;
    location_id: number;
    attending_physician: number;
    billing_physician: number;
    facility_id: number;
    referring_physician: string;
    dos: string;
    pos: string;
    bill_date: string;
    self_pay: boolean;
    pri_status: string;
    sec_status: string;
    oth_status: string;
    pat_status: string;
    pri_paid: number ;
    sec_paid: number ;
    oth_paid: number ;
    patient_paid: number ;
    allowed_amount: number ;
    write_off: number;
    claim_total: number ;
    amt_paid: number ;
    amt_due: number ;
    pa_number: string;
    employment: boolean;
    accident: boolean;
    accident_type: string;
    accident_date: string;
    accident_state: string;
    accident_auto: boolean;
    accident_other: boolean;
    accident_emergency: boolean;
    start_care_date: string;
    last_seen_date: string;
    current_illness_date: string;
    lmp_date: string;
    hospital_from_date: string;
    hospital_to_date: string;
    rebill_date: string;
    claim_number: string;
    draft: boolean;
    referral_number: string;
    luo: string;
    is_corrected: boolean;
    paper_payer_id: string;
    hcfa_17_a: string;
    is_resubmitted: boolean;
    medical_resubmision_code: string;
    is_process: boolean;
    eligibility_status: string;
    eligibility_inquiry_date: string;
    created_user: string;
    client_date_created: string;
    modified_user: string;
    client_date_modified: string;
    date_created: string;
    date_modified: string;
    xraydate: string;
    listcpticd: string;
    notes: string;
    
    system_ip: string;
    aa: boolean;
    coding_done_date: string;
    submission_status: string;
    is_hcfa: boolean;
    is_electronic: boolean;
    epsdt: boolean;
    lab_claim: boolean;
    outside_lab: boolean;
    outside_lab_charges: number ;
    not_bill: boolean;
    followup: boolean;
    hcfa_ins_type: string;
    icd_10_claim: boolean;
    bill_type_code: string;
    claim_type: string;
    eap:boolean;
    
    billing_provider_taxonomy:string;
}