export class ORMSaveAppointment {
    appointment_id:Number; 
    patient_id:Number; 
    appointment_date:String; 
    appointment_time:String; 
    appointment_duration:Number; 
    appointment_comments:String; 
    status_id:Number; 
    location_id:Number; 
    practice_id:Number; 
    provider_id:Number;    
    appsource:Number;
    apptype:Number; 
    appreason:Number;    
    created_user:String; 
    client_date_created:String; 
    modified_user:String; 
    client_date_modified:String; 
    date_created:String; 
    date_modified:String;
    system_ip:String;    
}