export class ORMSaveProviderTiming {
    timing_id:number;
    week_day:string;
    day_on:boolean;
    time_start:string;
    time_end:string;
    break_on:boolean;
    break_start:string;
    break_end:string;
    slot_size:number;
    created_user:string;
    date_created:string;
    modified_user:string;
    date_modified:string;
    client_date_created
    client_date_modified
    location_id:number;
    provider_id:number;
    practice_id:number;
    system_ip:string;
}